//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn1_QLTV_User_.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class DangKyTheTV
    {
        public int MaDangKyThe { get; set; }

        [DisplayName("Tài khoản")]
        [Required(ErrorMessage = "Không được bỏ trống!")]
        public string MaThe { get; set; }

        [DisplayName("Mật khẩu")]
        [Required(ErrorMessage = "Không được bỏ trống!")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [DisplayName("Nhập lại mật khẩu")]
        [Required(ErrorMessage = "Không được bỏ trống!")]
        [Compare("Password")]
        [DataType(DataType.Password)]
        [NotMapped]
        public string RePassword { get; set; }

        [DisplayName("Họ tên")]
        [Required(ErrorMessage = "Không được bỏ trống!")]
        public string HoTen { get; set; }

        [DisplayName("Ngày làm thẻ")]
        [Required(ErrorMessage = "Không được bỏ trống!")]
        public Nullable<System.DateTime> NgayLam { get; set; }
    }
}
