//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Code_KhoaLa.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class DauSach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DauSach()
        {
            this.Saches = new HashSet<Sach>();
        }
    
        [DisplayName("Mã Đầu Sách :")]
        [Required(ErrorMessage = "Vui Lòng Nhập Mã Đầu Sách!")]
        public int MaDauSach { get; set; }

        [DisplayName("Tên Sách :")]
        [Required(ErrorMessage ="Vui Lòng Nhập Tên Sách!")]
        public string TenSach { get; set; }

        [DisplayName("Tác Giả :")]
        [Required(ErrorMessage = "Vui Lòng Nhập Tác Giả của Sách!")]
        public string TacGia { get; set; }

        [DisplayName("Thể Loại :")]
        [Required(ErrorMessage = "Vui Lòng Nhập Thể Loại Sách!")]
        public string TheLoai { get; set; }

        [DisplayName("Năm Xuất Bản :")]
        [Required(ErrorMessage = "Vui Lòng Nhập Năm Xuất Bản!")]
        public Nullable<System.DateTime> NamXuatBan { get; set; }
        public string NhaXuatBan { get; set; }

        [DisplayName("Hình Ảnh Sách :")]
        [Required(ErrorMessage = "Vui Lòng Nhập file hình ảnh của Sách!")]
        public string HinhAnh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sach> Saches { get; set; }
    }
}
