//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn1_QuanLyThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        public int MaSach { get; set; }
        public string TenSach { get; set; }
        public string TenTacGia { get; set; }
        public string TheLoai { get; set; }
        public Nullable<int> NamXuatBan { get; set; }
        public string NXB { get; set; }
    }
}
